#!/bin/bash

function load_scripts_in_directory() {
    dir=$1
    if [ -d $dir ]; then
        for file in `ls $dir`; do
            source $dir/$file
        done
    fi
}

#for temp source file
load_scripts_in_directory ~/Library/bashes

#for temp source file
load_scripts_in_directory ~/alias/bashes

#for extend source file (from ~/alias/bashes)
load_scripts_in_directory ~/sh-extends